import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import image1 from "../../src/assets/images/Figure [image-anime].png";
import image2 from "../../src/assets/images/Figure [image-anime] (2).png";
import image3 from "../../src/assets/images/Figure [image-anime] (1).png";
import image4 from "../../src/assets/images/Figure [image-anime] (3).png";
import WhyUs from "../../src/assets/images/Why us.png";
export default function WhyUsSection() {
    return (_jsx("div", { className: "w-full py-20 px-6 lg:px-24", children: _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-20 items-start", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex flex-col items-start gap-2 mb-4", children: [_jsx("img", { src: WhyUs, alt: "Why us", className: "w-auto h-auto" }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("i", { className: "fa-solid fa-dumbbell text-[#ff4500] text-[20px]" }), _jsx("span", { className: "font-semibold tracking-wide text-[#ff4500]", children: "Why Us" })] })] }), _jsxs("h1", { className: "text-[40px] uppercase font-bold leading-tight mb-4", children: ["Elevate fitness with the", _jsx("span", { className: "text-[#ff4500]", children: " best way " }), " possible"] }), _jsx("p", { className: "text-[#242424] leading-relaxed mb-10", children: "We offer a fitness journey that\u2019s tailored to your goals, supported by professional trainers and a welcoming community. Whether it's weight loss, strength building, or overall wellness, our proven methods help you transform." }), _jsxs("div", { className: "relative", children: [_jsx("div", { className: "absolute left-7 top-0 bottom-0 w-[2px] border-l-2 border-dashed border-[#24242424]" }), _jsx(Step, { number: "01", title: "Personalized Fitness Plans", desc: "We tailor every workout to fit your unique goals and fitness level ensuring \r\n              that you make the most progress." }), _jsx(Step, { number: "02", title: "Results-Driven Focus", desc: "Everything we do is designed to help you achieve measurable results, \r\n              whether you're aiming for weight loss." }), _jsx(Step, { number: "03", title: "state-of-the-art equipment", desc: "We provide the latest in gym equipment, from cardio machines to free \r\n              weights, designed to support every type." })] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-6 mb-12", children: [_jsxs("div", { className: "flex flex-col gap-6", children: [_jsx("img", { src: image1, alt: "", className: "rounded-2xl w-full h-[360px] object-cover" }), _jsx("img", { src: image2, alt: "", className: "rounded-2xl w-full h-[360px] object-cover" })] }), _jsxs("div", { className: "flex flex-col gap-6", children: [_jsx("img", { src: image3, alt: "", className: "rounded-2xl w-full h-[300px] object-cover" }), _jsx("img", { src: image4, alt: "", className: "rounded-2xl w-full h-[300px] object-cover" })] })] })] }) }));
}
function Step({ number, title, desc }) {
    return (_jsxs("div", { className: "flex items-start gap-6 mb-12", children: [_jsx("div", { className: "relative z-10 w-14 aspect-square rounded-full\r\n        bg-[#ff4500] text-white flex items-center justify-center font-bold text-xl", children: number }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-lg", children: title }), _jsx("p", { className: "text-gray-600", children: desc })] })] }));
}
